apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-task-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-task-manager
  template:
    metadata:
      labels:
        app: devops-task-manager
    spec:
      containers:
        - name: devops-task-manager
          image: devops-task-manager:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 80
